=== devsoft91/RosaRosae/data/plants.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.w3schools.com"
  xmlns="http://www.w3schools.com"
  elementFormDefault="qualified">

  <xs:element name="plants">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="plant" type="Tplant" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:complexType name="Tplant">
    <xs:sequence>
      <xs:element name="date" type="xs:date"/>
      <xs:element name="author" type="xs:string"/>
      <xs:element name="title" type="xs:string"/>
      <xs:element name="img" type="Timg" minOccurs="0"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="specs" type="Tspecs"/>
      <xs:element name="paragraph" type="Tparagraph" maxOccurs="unbounded"/>
      <xs:element name="comments" type="Tcomments"/>
    </xs:sequence>
    <xs:attribute name="id" type="xs:positiveInteger" use="required"/>
  </xs:complexType>

  <xs:complexType name="Timg">
    <xs:attribute name="src" type="xs:anyURI" use="required"/>
    <xs:attribute name="alt" type="xs:string" use="required"/>
  </xs:complexType>

  <xs:complexType name="Tspecs">
    <xs:sequence>
      <xs:element name="family" type="xs:string"/>
      <xs:element name="height" type="xs:string"/>
      <xs:element name="diameter" type="xs:string"/>
      <xs:element name="light" type="Tlight"/>
      <xs:element name="terrain" type="Tterrain"/>
      <xs:element name="temperature" type="xs:integer"/>
      <xs:element name="ph" type="empty" minOccurs="0" maxOccurs="1"/>
      <xs:element name="hiquality" type="empty" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="Tlight">
    <xs:restriction base="xs:string">
      <xs:enumeration value="soleggiato"/>
      <xs:enumeration value="penombra"/>
      <xs:enumeration value="ombra"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="Tterrain">
    <xs:restriction base="xs:string">
      <xs:enumeration value="asciutto"/>
      <xs:enumeration value="umido"/>
      <xs:enumeration value="bagnato"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Tparagraph">
    <xs:sequence>
      <xs:element name="text" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="title" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="Tcomments">
    <xs:sequence>
      <xs:element name="comment" type="Tcomment" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Tcomment">
    <xs:sequence>
      <xs:element name="date" type="xs:date"/>
      <xs:element name="time" type="xs:time"/>
      <xs:element name="user" type="xs:string"/>
      <xs:element name="text" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="valid" type="xs:boolean" default="false"/>
  </xs:complexType>

  <xs:complexType name="empty"/>

</xs:schema>

=== devsoft91/RosaRosae/data/plants.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../plants.xsl"?>
<plants xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="http://www.plants.com plants.xsd">

  <plant id="1">
    <date>2014-03-20</date>
    <author>EnricoCeron</author>
    <title>Malus Sargentii</title>
    <img src="../img/Malus_sargentii.jpg" alt="Un'immagine dell'arbusto in fiore"/>
    <specs>
      <family>rosaceae</family>
      <height>5 metri</height>
      <diameter>5 metri</diameter>
      <light>soleggiato</light>
      <terrain>asciutto</terrain>
      <temperature>-15</temperature>
    </specs>
    <description>Un arbusto di modeste dimensioni a foglia caduca che fiorisce in primavera.</description>
    <paragraph title="Aspetto">Arbusto a portamento espanso, spinoso, spesso con l'età simile a un albero.</paragraph>
    <paragraph title="Fiori">A forma di coppa, riuniti in infiorescenze, di colore bianco brillante. Fine primavera.</paragraph>
    <paragraph title="Frutti">Di lunga durata, globosi, simili a bacche, di colore rosso intenso.</paragraph>
    <paragraph title="Foglie">Caduche, ovali, talvolta lobate, di colore verde scuro.</paragraph>
    <paragraph title="Zona d'origine">Boschi e foreste del Giappone.</paragraph>
    <paragraph title="Coltivazione">Tollera le condizioni di moderato ombreggiamento e si adatta a tutti i tipi di terreno, tranne quelli soggetti a ristagno idrico. In inverno è consigliabile, se necessario, eliminare il legno morto o ammalato. Può essere sensibile al fuoco batterico. Si tratta di un bell'arbusto con una lunga stagione di interesse, ben fornito di fiori durante la primavera e ricco di piccoli frutti simili a ciliegie in autunno. È adatta ai piccoli giardini e può essere coltivato in siepi o come esemplare isolato in un prato.</paragraph>
    <paragraph title="Propagazione">Per talea alla fine dell'estate o per innesto in inverno.</paragraph>
    <comments>
    </comments>
  </plant>

  <plant id="2">
    <date>2014-03-28</date>
    <author>EnricoCeron</author>
    <title>Corylus comune contorto</title>
    <img src="../img/corylus.jpg" alt="Un dettaglio della pianta spoglia in fiore"/>
    <specs>
      <family>corylaceae</family>
      <height>6 metri</height>
      <diameter>6 metri</diameter>
      <light>soleggiato</light>
      <terrain>asciutto</terrain>
      <temperature>-15</temperature>
      <hiquality/>
    </specs>
    <description>Arbusto particolare a foglia caduca che fiorisce tra gennaio e febbraio.</description>
    <paragraph title="Aspetto">A portamento arbustivo, con rami spiralati.</paragraph>
    <paragraph title="Fiori">Gattici penduli, di colore giallo pallido. Fine inverno.</paragraph>
    <paragraph title="Foglie">Caduche, quasi rotonde, appuntite, finemente dentate, verdi.</paragraph>
    <paragraph title="Zona d'origine">Ottenuta in Inghilterra nel 1863.</paragraph>
    <paragraph title="Coltivazione">Tollera le condizioni di moderato ombreggiamento e si adatta a qualsiasi terreno fertile, anche se calcareo. Possiede un bell'aspetto invernale ed è utile per composizioni floreali.</paragraph>
    <paragraph title="Propagazione">Per innesto a fine estate o per propaggine tra fine autunno e inizio primavera.</paragraph>
    <comments>
    </comments>
  </plant>

  <plant id="3">
    <date>2014-04-02</date>
    <author>EnricoCeron</author>
    <title>Iris cristata</title>
    <img src="../img/i_cristata.jpg" alt="Un'immagine del fiore"/>
    <specs>
      <family>iridaceae</family>
      <height>10 centimetri</height>
      <diameter>30 centimetri</diameter>
      <light>penombra</light>
      <terrain>umido</terrain>
      <temperature>-15</temperature>
      <ph/>
    </specs>
    <description>Piccolo fiore ornamentale.</description>
    <paragraph title="Aspetto">Rizomatoso.</paragraph>
    <paragraph title="Fiori">Larghi fino a 4 centimetri, quasi privi di steli, in numero di 1-2 per stelo, di colore lilla, blu, lavanda o bianco, con ali e creste di colore arancio.</paragraph>
    <paragraph title="Foglie">A forma di spada, di colore giallo-verde.</paragraph>
    <paragraph title="Coltivazione">Preferisce i terreni umidi senza calce.</paragraph>
    <comments>
      <comment valid="true">
        <date>2014-06-01</date>
        <time>10:46:26</time>
        <user>GiacomoBeltrame</user>
        <text>bella pianta</text>
      </comment>
</comments>
  </plant>

  <plant id="4">
    <date>2014-04-19</date>
    <author>EnricoCeron</author>
    <title>Ranuncolo a foglie di Aconito</title>
    <img src="../img/ranunculus-aconitifolius.jpg" alt="Un'immagine del fiore sbocciato"/>
    <specs>
      <family>ranunculaceae</family>
      <height>1 metro</height>
      <diameter>1 metro</diameter>
      <light>soleggiato</light>
      <terrain>umido</terrain>
      <temperature>-15</temperature>
    </specs>
    <description>Piccolo fiore selvaggio d'ornamento. Bianco, sboccia in primavera.</description>
    <paragraph title="Aspetto">Robusto e cespitoso.</paragraph>
    <paragraph title="Fiori">Semplici, a coppa, larghi fino a 2,5 centimetri, bianchi talvolta con sfumature rosa, in primavera e all'inizio dell'estate.</paragraph>
    <paragraph title="Foglie">A 3 o 5 lobi, di colore verde scuro.</paragraph>
    <paragraph title="Zona d'origine">Prati subalpini e rive di corsi d'acqua, dall'Europa occidentale a quella centrale.</paragraph>
    <paragraph title="Coltivazione">In terreno fertile, umido, ricco di humus e al sole. Per un giardino di fiori selvatici, un bordo erbaceo o lungo un fiume al di sotto del livello dell'acqua.</paragraph>
    <paragraph title="Propagazione">Per seme in primavera o per divisione in primavera e in autunno.</paragraph>
    <comments>
    </comments>
  </plant>

  <plant id="5">
    <date>2014-04-22</date>
    <author>EnricoCeron</author>
    <title>Impatiens Repens</title>
    <img src="../img/impatiens_repens.jpg" alt="Immagine del particolare fiore giallo"/>
    <specs>
      <family>balsaminaceae</family>
      <height>10 centimetri</height>
      <diameter>indefinito</diameter>
      <light>soleggiato</light>
      <terrain>umido</terrain>
      <temperature>-10</temperature>
      <hiquality/>
    </specs>
    <description>Pianta tappezzante dal fiore particolare, coltivabile sia all'interno che all'esterno.</description>
    <paragraph title="Aspetto">Strisciante con fusti che radicano al suolo.</paragraph>
    <paragraph title="Fiori">A 5 petali con grande sperone ricoperto di sottile peluria, giallo intenso, in estate.</paragraph>
    <paragraph title="Foglie">Sempreverdi, dentellate, reniformi, di colore verde.</paragraph>
    <paragraph title="Zona d'origine">Sri Lanka e India.</paragraph>
    <paragraph title="Coltivazione">In zone rigide come pianta da serra o appartamento, in terriccio umido e ben drenato. Se coltivato all'esterno richiede un'esposizione soleggiata. Ricopre il terreno in un bordo erbaceo o misto.</paragraph>
    <paragraph title="Propagazione">Per seme o per talea di stelo, in primavera o in estate.</paragraph>
    <comments>
      <comment valid="true">
        <date>2014-05-16</date>
        <time>09:55:32</time>
        <user>EnricoCeron</user>
        <text>basta, non tocco più niente</text>
      </comment>
      <comment valid="true">
        <date>2014-05-16</date>
        <time>10:31:11</time>
        <user>GiacomoBeltrame</user>
        <text>lol</text>
      </comment>
          <comment valid="true">
        <date>2014-06-22</date>
        <time>17:43:11</time>
        <user>EnricoCeron</user>
        <text>come non detto...</text>
      </comment>
</comments>
  </plant>

  <plant id="6">
    <date>2014-06-25</date>
    <author>GiacomoBeltrame</author>
    <title>Ciclamino</title>
    <img src="../img/ciclamino.jpg" alt="Un'immagine del fiore del ciclamino"/>
    <specs>
      <family>primulaceae</family>
      <height>15 centimetri</height>
      <diameter>20 centimetri</diameter>
      <light>ombra</light>
      <terrain>umido</terrain>
      <temperature>0</temperature>
    </specs>
    <description>Fiore selvatico amante dell'ombra.</description>
    <paragraph title="Fiori">Genera delicati fiori rosati. I fiori sono zigomorfi, pentameri (calice e corolla con 5 elementi) e tetraciclici (formati da quattro elementi: calice – corolla – androceo – gineceo). Del fiore la parte persistente è il calice a sostegno del frutto.</paragraph>
    <paragraph title="Foglie">Le foglie sono unicamente basali a forme varie ma sempre indivise e con un lungo picciolo. La pagina superiore può essere macchiata variamente di bianco, mentre quella inferiore può presentare delle screziature rosseggianti in proseguimento del picciolo, rossastro pure lui.</paragraph>
    <paragraph title="Frutti">Il frutto è una capsula sferica uniloculare deiscente. I semi contenuti nel frutto sono più o meno tondi con circa 1 - 2 millimetri di diametro; raggiungono la maturità dopo un anno dalla fioritura.</paragraph>
    <paragraph title="Distribuzione">Si distribuiscono attorno al bacino del Mediterraneo.</paragraph>
    <paragraph title="Coltivazione">In vaso o in terra, ambienti freschi, umidi e protetti dal sole estivo con terriccio di foglie e letame mescolato a sabbia.</paragraph>
    <paragraph title="Propagazione">Normalmente per seme o per divisione del tubero se esemplari piu grossi.</paragraph>
    <comments>
    </comments>
  </plant>
  
  <plant id="7">
    <date>2014-06-27</date>
    <author>GiacomoBeltrame</author>
    <title>Viola</title>
    <img src="../img/viola.jpg" alt="immagine del fiore della viola"/>
    <specs>
      <family>Violaceae</family>
      <height>15 centimetri</height>
      <diameter>10 centimetri</diameter>
      <light>penombra</light>
      <terrain>umido</terrain>
      <temperature>0</temperature>
      <hiquality/>
    </specs>
    <description>Fiori annuali o perenni dai colori caratteristici.</description>
